export { default as Nav } from './Nav/Nav'
export { default as SignIn } from './SignIn/SignIn'
export { default as Graph } from './Graph/Graph'
export { default as HomePage } from './HomePage/HomePage'
export { default as LeaderBoard } from './Leaderboard/Leaderboard'
// export { default as Info } from './Info/Info1'
// export { default as Info } from './Info/Info2'
